name: larastan

on: workflow_call

jobs:
  larastan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
        env:
          GITHUB_TOKEN: "${{ secrets.MY_TOKEN }}"

      - name: Remove local dependencies
        run: composer config repositories.local --unset

      - name: Install PHP dependencies
        run: composer install --no-interaction --quiet --no-progress --ansi

      - name: Execute Static Analysis Tool
        run: ./vendor/bin/phpstan analyse --ansi
